stages:
  - build
  - test
  - sonarqube_stage
  - docker_stage
build:
  stage: build
  script:
    - cd backend
    - ./gradlew build -x test
    - ./gradlew.bat --stop
test:
  stage: test
  script:
    - cd backend
    - ./gradlew test
    - ./gradlew.bat --stop
sonarqube_ci_stanza:
  stage: sonarqube_stage
  script:
    - cd backend
    - ./gradlew test jacocoTestReport sonarqube
    - ./gradlew.bat --stop
image: docker:latest
services:
  - docker:dind
docker_build:
  stage: docker_stage
  script:
    - docker build -t nurnechushtan/flyaway-nur-nechushtan-backend:latest -f backend/Dockerfile backend
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker push nurnechushtan/backend:latest
    #- docker push "$REGISTRY_USER"/backend:latest -f backend/Dockerfile
    #- docker push nurnechushtan/flyaway:frontend
    #- docker-compose -f Docker-compose.yml down
    #- docker-compose -f Docker-compose.yml build --pull
    #- docker-compose -f Docker-compose.yml up -d --build
