stages:
  - build
  - test
  - cypress_stage
  - sonarqube_stage
  - docker_stage
build:
  stage: build
  script:
    - cd backend
    - ./gradlew build -x test
    - ./gradlew.bat --stop
test:
  stage: test
  script:
    - cd backend
    - ./gradlew test
    - ./gradlew.bat --stop
cypress_stage:
  stage: cypress_stage
  script:
    - cd frontend
    #- npm install
    - concurrently "cd backend && ./gradlew bootRun" "cd frontend && npm start" "cd frontend && npx cypress run"
sonarqube_ci_stanza:
  stage: sonarqube_stage
  script:
    - cd backend
    - ./gradlew test jacocoTestReport sonarqube
    - ./gradlew.bat --stop
docker_build:
  stage: docker_stage
  script:
    - docker-compose -f Docker-compose.yml down
    - docker-compose -f Docker-compose.yml build --pull
    #- docker-compose -f Docker-compose.yml up -d --build
