stages:
  - build
  - test
  - cypress_stage
  - sonarqube_stage
  - docker_stage
build:
  stage: build
  script:
    - cd backend
    - ./gradlew build -x test
    - ./gradlew.bat --stop
test:
  stage: test
  script:
    - cd backend
    - ./gradlew test
    - ./gradlew.bat --stop
cypress_stage:
  stage: cypress_stage
  script:
    - start cmd /c "cd backend && ./gradlew bootRun"
    - timeout /t 10
    - start cmd /c "cd frontend && npm start"
    - start cmd /c "cd frontend && npx cypress run"
    - taskkill /im cmd.exe /f
sonarqube_ci_stanza:
  stage: sonarqube_stage
  script:
    - cd backend
    - ./gradlew test jacocoTestReport sonarqube
    - ./gradlew.bat --stop
docker_build:
  stage: docker_stage
  script:
    - docker-compose -f Docker-compose.yml down
    - docker-compose -f Docker-compose.yml build --pull
    #- docker-compose -f Docker-compose.yml up -d --build
