stages:
  - build
  - test
  - sonarqube_stage
build:
  stage: build
  script:
    - cd backend
    - ./gradlew build -x test
    - ./gradlew.bat --stop
docker_build:
  stage: build
  script:
    - docker-compose -f docker-compose-ci.yml build --pull
test:
  stage: test
  script:
    - cd backend
    - ./gradlew test
    - ./gradlew.bat --stop
sonarqube_ci_stanza:
  stage: sonarqube_stage
  script:
    - cd backend
    - ./gradlew sonarqube
    - ./gradlew.bat --stop
