version: '3'
services:

  dbpostgresql:
    image: postgres:latest
    container_name: postgres
    volumes:
      - individual-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flyaway_db
    restart: unless-stopped

  backend:
    build: ./backend
    restart: on-failure
    container_name: backend
    links:
      - dbpostgresql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_URL=jdbc:postgresql://dbpostgresql:5432/flyaway_db
    ports:
      - 8081:8080
    depends_on:
      - dbpostgresql

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000

volumes:
  individual-data:
