stages:
  - build
  - sonarqube_stage
  - test
build:
  stage: build
  script:
    - ./gradlew build -x test
    - ./gradlew.bat --stop
test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat --stop
sonarqube_ci_stanza:
  stage: sonarqube_stage
  script:
    - ./gradlew sonarqube
    - ./gradlew.bat --stop
